version: '3.1'
services:
    mysql:
        command: --default-authentication-plugin=mysql_native_password
        environment:
           MYSQL_ROOT_PASSWORD: javier_mysql
        image: mysql
        ports:
          - "3306:3306"
        restart: always  