version: 2.1

jobs:
    test:
      machine:
        image: ubuntu-1604:201903-01
      working_directory: ~/project-nodejs
      steps:
        - checkout
        - run:
            name: Install Docker Compose
            command: |
              set -x
              curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > docker-compose
              sudo mv docker-compose /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
        - run:
            name: Install Node js 
            command: |
              curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
              sudo apt-get install -y nodejs  
        - run: 
            name: install dependencies and exec tests
            command: |
              node --version
              npm --version
              docker-compose -f ./docker-mysql/docker-compose.yml up -d      
        - run:
            name: install packages
            command: npm install
        - run:
            name: Running unit test
            command: npm test 



workflows:
  build-and-deploy:
      jobs:
        - test