version: 2.1

jobs:
    test:
      docker:
        - image: circleci/node:14.4
        - image: mysql 
          command: --default-authentication-plugin=mysql_native_password
          environment:
            MYSQL_ROOT_PASSWORD: javier_mysql
      steps:
        - checkout
        - run:
            name: install packages
            command: npm install
        - run:
            name: Running unit test
            command: npm test 


workflows:
  build-and-deploy:
      jobs:
        - test