version: 2.1

orbs:
    node: circleci/node@3.0.0

jobs:
    test:
      docker:
        - image: circleci/node:14.4
      steps:
        - checkout
        - run:
            name: install packages
            command: npm install
        - run:
            name: Running unit test
            command: npm test

    docker:        
        - run:
            name: Docker databases
            command: cd docker-mysql   
        - run:
            name: Docker databases
            command: docker-compose up -d   


workflows:
  build-and-deploy:
      jobs:
        - docker
        - test