version: 2.1

orbs:
    node: circleci/node@3.0.0

jobs:
    test:
      docker:
        - image: circleci/node:14.4
      steps:
        - checkout
        - run: 
            name: Running docker
            command: docker-compose -f ./docker-mysql/docker-compose.yml up -d
        - run:
            name: install packages
            command: npm install
        - run:
            name: Running unit test
            command: npm test 



workflows:
  build-and-deploy:
      jobs:
        - test